Allow a label in a link to another document text
ruby/rdoc pull request #804
Opened 2021-04-09 16:59 UTC by nobu

2021-04-09 22:51 UTC, olleolleolle approved these changes
👍 As the tests show, this adds URL fragment support to the these links.

2021-06-30 17:38 UTC, aycabta requested changes

2021-06-30 17:38 UTC, aycabta commented on test/rdoc/test_rdoc_markup_to_html.rb
>    def test_gen_url_rdoc_file
```ruby
    assert_equal '<a href="example_md.html">example</a>',
                 @to.gen_url('example.md', 'example')
```

Needs this one, and still failed.

2021-07-01 14:56 UTC, aycabta approved these changes

2021-07-01 15:23 UTC, aycabta commented
💪

2021-07-01 15:23 UTC, merged