Markup reference
ruby/rdoc pull request #824
Opened 2021-07-14 12:51 UTC by BurdetteLamar

This PR is proposed as a replacement for the section "[RDoc Markup Reference](https://docs.ruby-lang.org/en/2.1.0/RDoc/Markup.html#class-RDoc::Markup-label-RDoc+Markup+Reference)"  in the documentation for class RDoc::Markup. The PR covers the topics found there.

I've built this as the separate "dummy" class RDoc::MarkupReference to allow examples of on-page links and references.  This avoids adding illustrative dummy code in the class RDoc::Markup itself.

There are some specific questions and requests for reviewers, specifically where:
- I thought that the RDoc behavior may be wrong.
- I was not able to craft an example as I'd like.

I'm marking this as a draft at least until those issues are resolved.

2021-07-14 18:12 UTC, jeremyevans reviewed
Seems strange to add this in a place where it could be required.  Since this is only for documentation purposes, having this file under `lib` seems wrong.

I did a very brief review and don't see major issues with the text. I don't know the answer to any of the questions, though.

Note that I'm not an rdoc maintainer, and probably not a good person to review this.

2021-07-14 18:37 UTC, BurdetteLamar commented
> Seems strange to add this in a place where it could be required. Since this is only for documentation purposes, having this file under `lib` seems wrong.
> 
> I did a very brief review and don't see major issues with the text. I don't know the answer to any of the questions, though.
> 
> Note that I'm not an rdoc maintainer, and probably not a good person to review this.

Thanks, @jeremyevans.  Your ideas, as always, are helpful.  I can move the file do new directory doc/,
which also requires citing it in the Rakefile.  Does that make sense?

2021-07-14 20:06 UTC, BurdetteLamar commented
I have moved the dummy class MarkupReference from lib/ to new directory /doc, and have added the file to the Rakefile so that it will be built into the documentation.

2021-07-26 13:40 UTC, aycabta requested changes
Okay, I think this is a good patch. It's a very valuable document. However, there are too many commits, would you squash them into one?

2021-07-26 14:02 UTC, BurdetteLamar commented
> 
> 
> Okay, I think this is a good patch. It's a very valuable document. However, there are too many commits, would you squash them into one?
Can I just use the "Squash and merge" button here?

2021-07-28 13:16 UTC, BurdetteLamar commented
@aycabta, can you suggest someone to answer the "Reviewers:" questions embedded in this PR?

2021-07-30 13:54 UTC, BurdetteLamar commented
@aycabta, do you want this PR to be squashed and merged, even with its remaining questions unanswered?

2021-08-04 15:39 UTC, BurdetteLamar commented
@nobu or @hsbt, can you help?  Or suggest someone to help?  @aycabta has approved this, but I don't want to merge until the six questions are answered, one way or another.  Each is tagged with "Reviewers:".

2021-08-05 04:05 UTC, hsbt commented
> six questions are answered

What's this? I didn't found them in this pr.

2021-08-05 06:45 UTC, olleolleolle commented on doc/markup_reference.rb
> +#    [Reviewers: This did not work; should it?]
(This is me sign-posting where there are direct questions in this diff, to try making it easier to locate them. I'll quote the question text.)

> [Reviewers: This did not work; should it?]

2021-08-05 06:46 UTC, olleolleolle commented on doc/markup_reference.rb
> +#     [Reviewers: This link did not work. Should it?]
(This is me sign-posting where there are direct questions in this diff, to try making it easier to locate them. I'll quote the question text.)

> [Reviewers: This link did not work; should it?]

2021-08-05 06:46 UTC, olleolleolle commented on doc/markup_reference.rb
> +#     [Reviewers: This link did not work. Should it?]
> [Reviewers: This link did not work. Should it?]

2021-08-05 06:46 UTC, olleolleolle commented on doc/markup_reference.rb
> +#     [Reviewers: This link did not work. Should it?]
> [Reviewers: This link did not work. Should it?]

2021-08-05 06:46 UTC, olleolleolle commented on doc/markup_reference.rb
> +#     [Reviewers: This link not did work. Should it?]
> [Reviewers: This link did not work. Should it?]

2021-08-05 06:47 UTC, olleolleolle commented on doc/markup_reference.rb
> +#     [Reviewers: What file reference would work?]
> [Reviewers: What file reference would work]

2021-08-05 07:09 UTC, hsbt commented
@olleolleolle Thanks! I got them.

2021-08-05 15:05 UTC, BurdetteLamar commented
@olleolleolle, thanks much!

2021-08-06 19:44 UTC, BurdetteLamar commented
So, @Team, how does this get finished up?

As I said in the original comment, this covers the same topics as in the old markup reference.  There's much more that can be added -- topics not previously covered.  I'm eager to continue, but first need to get this finished and merged.

2021-08-10 17:18 UTC, BurdetteLamar commented
I removed the 6 questions that were embedded in the text.

Now I find that I can no longer push to here:

  remote: fatal error in commit_refs
  To https://github.com/BurdetteLamar/rdoc.git
  ! [remote rejected]   markup_reference -> markup_reference (failure)
  error: failed to push some refs to 'https://github.com/BurdetteLamar/rdoc.git'

If no one objects, I'll close this and open another PR that will be ready to merge.

2021-08-18 16:01 UTC, BurdetteLamar commented
@aycabta , still waiting for final approval (or disapproval).

2021-09-03 10:31 UTC, aycabta commented
Sorry, I think I'll get some time to review later this month. Give me a little longer.

2021-09-03 12:36 UTC, BurdetteLamar commented
> 
> 
> Sorry, I think I'll get some time to review later this month. Give me a little longer.

Thanks, and no rush.  Glad to know you're still interested.

2021-12-01 19:02 UTC, BurdetteLamar commented
@aycabta, can you review this PR?  Or suggest someone else who can?

2022-01-20 22:49 UTC, BurdetteLamar commented
@aycabta, any progress on this?

2022-02-22 14:23 UTC, BurdetteLamar commented
@aycabta, there is much more that can be done with the RDoc documentation, but that can't be started until this PR is merged.  Is there anything more that needs to be done here?

2022-03-12 20:33 UTC, BurdetteLamar commented
@aycabta, can this be reviewed by someone else?  I'm thinking maybe @jeremyevans or @peterzhu2118.  If not, where are we with this?

2022-03-14 17:12 UTC, BurdetteLamar commented
Somehow I thought that @aycabta is the maintainer for RDoc; now I see that the maintainers are @drbrain and @hsbt.  Can one of you review this PR?

2022-03-14 17:14 UTC, BurdetteLamar commented
To avoid confusion, note that the "six questions" mentioned above are moot, and no longer relevant.

2022-03-18 19:10 UTC, BurdetteLamar commented
> Okay, I think this is a good patch. It's a very valuable document. However, there are too many commits, would you squash them into one?

That's from @aycabta, many months ago, yet I can't get a review from any committer, not even the RDoc maintainers?  I'm baffled.

2022-03-19 00:24 UTC, hsbt commented
@BurdetteLamar see https://twitter.com/aycabta/status/1458494862202789893

Not everyone has enough time, motivation, and health for the all-time. Your rush request seems rude attitude.

2022-03-19 08:38 UTC, hsbt commented
Your contribution is valuable, I understand. After 1 year, there is no response from @aycabta . I will manage this.

Please wait a while.

2022-03-19 12:50 UTC, BurdetteLamar commented
Thanks, @hsbt.

2022-05-15 11:53 UTC, adam12 commented on doc/markup_reference.rb
> +#   Parameter +type+ is one of +markdown+, +rd+, +rdoc+, +tomcat+.
```suggestion
#   Parameter +type+ is one of +markdown+, +rd+, +rdoc+, +tomdoc+.
```

2022-07-11 17:58 UTC, BurdetteLamar commented
> Your contribution is valuable, I understand. After 1 year, there is no response from @aycabta . I will manage this.
> 
> Please wait a while.

@hsbt, may I have your permission to recruit reviewers for this PR?

2022-07-11 23:17 UTC, merged